"""add_is_admin_to_user

Revision ID: 8656185f8af5
Revises: b4cef2acedf7
Create Date: 2026-07-01 18:13:00.149131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8656185f8af5'
down_revision: Union[str, None] = 'b4cef2acedf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_constraint('fk_user_wearer_person_id', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'person', ['wearer_person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('fk_user_wearer_person_id', 'user', 'person', ['wearer_person_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
