"""drop_entity_embedding_vector

Revision ID: 9fbc406ce2b9
Revises: af056275ab6a
Create Date: 2026-06-24 10:56:19.719611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9fbc406ce2b9'
down_revision: Union[str, None] = 'af056275ab6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_embedding', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_embedding', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
